-- Database: mboard

-- DROP DATABASE mboard;

CREATE DATABASE hrms
  WITH OWNER = mboard
       ENCODING = 'UTF8'
       TABLESPACE = pg_default
       LC_COLLATE = 'en_US.UTF-8'
       LC_CTYPE = 'en_US.UTF-8'
       CONNECTION LIMIT = -1;

ALTER DATABASE hrms
  SET search_path = pg_catalog, public, docrep, reports, translation, audit;
GRANT CONNECT, TEMPORARY ON DATABASE hrms TO public;
GRANT ALL ON DATABASE hrms TO mboard;
GRANT CONNECT ON DATABASE hrms TO zabbix;

ALTER DEFAULT PRIVILEGES 
    GRANT INSERT, SELECT, UPDATE, DELETE, TRUNCATE, REFERENCES, TRIGGER ON TABLES
    TO postgres;

ALTER DEFAULT PRIVILEGES 
    GRANT INSERT, SELECT, UPDATE, DELETE, TRUNCATE, REFERENCES, TRIGGER ON TABLES
    TO devshoesdemorole;

ALTER DEFAULT PRIVILEGES 
    GRANT SELECT ON TABLES
    TO "mbReport";

ALTER DEFAULT PRIVILEGES 
    GRANT SELECT, UPDATE, USAGE ON SEQUENCES
    TO postgres;

ALTER DEFAULT PRIVILEGES 
    GRANT SELECT, UPDATE, USAGE ON SEQUENCES
    TO devshoesdemorole;

ALTER DEFAULT PRIVILEGES 
    GRANT EXECUTE ON FUNCTIONS
    TO public;

ALTER DEFAULT PRIVILEGES 
    GRANT EXECUTE ON FUNCTIONS
    TO postgres;

ALTER DEFAULT PRIVILEGES 
    GRANT EXECUTE ON FUNCTIONS
    TO devshoesdemorole;

ALTER DEFAULT PRIVILEGES 
    GRANT USAGE ON TYPES
    TO public;

ALTER DEFAULT PRIVILEGES 
    GRANT USAGE ON TYPES
    TO postgres;

ALTER DEFAULT PRIVILEGES 
    GRANT USAGE ON TYPES
    TO devshoesdemorole;


/*
Commando de dump
pg_dump devtemplate | psql hrms
*/